# Generated by Django 4.0.3 on 2022-03-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['-date_added']},
        ),
    ]
