# Generated by Django 4.0.3 on 2022-03-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0002_alter_userimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('notification', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
