# Generated by Django 4.0.3 on 2022-03-24 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0004_notifications_opuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='ptitle',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
