# Generated by Django 4.0.3 on 2022-03-24 09:40

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0006_pendingresume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('userimg', models.ImageField(upload_to='')),
                ('fullname', models.CharField(max_length=80)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='user', unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('designation', models.CharField(max_length=80)),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('skill1', models.CharField(max_length=50)),
                ('skill2', models.CharField(max_length=50)),
                ('skill3', models.CharField(max_length=50)),
                ('skill4', models.CharField(max_length=50)),
                ('skill5', models.CharField(max_length=50)),
                ('lang1', models.CharField(max_length=50)),
                ('lang2', models.CharField(max_length=50)),
                ('lang3', models.CharField(max_length=50)),
                ('lang4', models.CharField(max_length=50)),
                ('extitle', models.CharField(max_length=100)),
                ('excompany', models.CharField(max_length=100)),
                ('exstart', models.CharField(max_length=50)),
                ('exend', models.CharField(max_length=50)),
                ('exsummary', models.TextField()),
                ('edtitle', models.CharField(max_length=100)),
                ('eduniversity', models.CharField(max_length=50)),
                ('edend', models.CharField(max_length=50)),
                ('edsummary', models.TextField()),
                ('mylink', models.URLField()),
                ('slink1', models.URLField()),
                ('slink2', models.URLField()),
                ('slink3', models.URLField()),
                ('slink4', models.URLField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
