# Generated by Django 4.0.3 on 2022-03-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0008_alter_approvedresume_user_alter_pendingresume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedresume',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pendingresume',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
