# Generated by Django 4.0.3 on 2022-03-26 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0010_alter_approvedresume_user_alter_pendingresume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedproject',
            name='about',
        ),
        migrations.RemoveField(
            model_name='pendingproject',
            name='about',
        ),
    ]
