# Generated by Django 4.0.3 on 2022-03-27 02:05

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0011_remove_approvedproject_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=200)),
                ('projuser', models.CharField(max_length=50)),
                ('projsender', models.CharField(max_length=50)),
                ('senderimg', models.ImageField(upload_to='')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='projsender', unique=True)),
                ('price', models.IntegerField()),
                ('days', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
