# Generated by Django 4.0.3 on 2022-03-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0012_proposals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposals',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='proposals',
            name='currency',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
