# Generated by Django 4.0.3 on 2022-03-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0014_remove_proposals_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedresume',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingresume',
            name='number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
