# Generated by Django 4.0.3 on 2022-03-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0015_approvedresume_number_pendingresume_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedresume',
            name='number',
        ),
        migrations.RemoveField(
            model_name='pendingresume',
            name='number',
        ),
    ]
