# Generated by Django 4.0.3 on 2022-03-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0016_remove_approvedresume_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposals',
            name='number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
