# Generated by Django 4.0.3 on 2022-03-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0017_proposals_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=50)),
                ('senderimg', models.ImageField(upload_to='')),
                ('receiver', models.CharField(max_length=50)),
                ('receiverimg', models.ImageField(upload_to='')),
                ('fullname', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
