# Generated by Django 4.0.3 on 2022-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0018_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ongoingproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('posted', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('hiredon', models.DateField(auto_now_add=True)),
                ('hireduser', models.CharField(max_length=50)),
                ('hfullname', models.CharField(max_length=70)),
                ('himage', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['-hiredon'],
            },
        ),
    ]
