# Generated by Django 4.0.3 on 2022-03-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0020_ongoingproject_currency_ongoingproject_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ongoingproject',
            name='hfullname',
        ),
        migrations.AddField(
            model_name='ongoingproject',
            name='hfname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ongoingproject',
            name='hlname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
