# Generated by Django 4.0.3 on 2022-03-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0021_remove_ongoingproject_hfullname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completedproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('rate', models.IntegerField()),
                ('hiredon', models.CharField(max_length=20)),
                ('hireduser', models.CharField(max_length=50)),
                ('hfname', models.CharField(max_length=50)),
                ('hlname', models.CharField(max_length=50)),
                ('himage', models.ImageField(upload_to='')),
                ('completed', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed'],
            },
        ),
    ]
