# Generated by Django 4.0.3 on 2022-03-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0022_completedproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfname', models.CharField(max_length=50)),
                ('rlname', models.CharField(max_length=50)),
                ('ruser', models.CharField(max_length=50)),
                ('rimg', models.ImageField(upload_to='')),
                ('hireduser', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
