# Generated by Django 4.0.3 on 2022-03-29 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0025_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='recipent',
        ),
    ]
