# Generated by Django 4.0.3 on 2022-04-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0026_rename_recipient_message_recipent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='fullname',
        ),
        migrations.AddField(
            model_name='messages',
            name='rfullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='sfullname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
