# Generated by Django 4.0.3 on 2022-04-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0027_remove_messages_contact_remove_messages_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='rfullname',
            new_name='sname',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sfullname',
        ),
        migrations.AddField(
            model_name='messages',
            name='rname',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
