# Generated by Django 4.0.3 on 2022-04-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidlance', '0028_rename_rfullname_messages_sname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='receiverimg',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='rname',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='senderimg',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='sname',
        ),
    ]
